// Starter database hero MLBB. Foto hero boleh ditambahkan nanti lewat field image.
window.HCI_HEROES = [
  { id:"akai", name:"Akai", lanes:["Roam","Jungle"], image:"", active:true },
  { id:"aldous", name:"Aldous", lanes:["EXP Lane"], image:"", active:true },
  { id:"alice", name:"Alice", lanes:["EXP Lane","Mid Lane"], image:"", active:true },
  { id:"alpha", name:"Alpha", lanes:["Jungle","EXP Lane"], image:"", active:true },
  { id:"alucard", name:"Alucard", lanes:["Jungle","EXP Lane"], image:"", active:true },
  { id:"angela", name:"Angela", lanes:["Roam"], image:"", active:true },
  { id:"argus", name:"Argus", lanes:["EXP Lane"], image:"", active:true },
  { id:"arlott", name:"Arlott", lanes:["EXP Lane","Roam"], image:"", active:true },
  { id:"atlas", name:"Atlas", lanes:["Roam"], image:"", active:true },
  { id:"aulus", name:"Aulus", lanes:["Jungle","EXP Lane"], image:"", active:true },
  { id:"aurora", name:"Aurora", lanes:["Mid Lane"], image:"", active:true },
  { id:"badang", name:"Badang", lanes:["EXP Lane"], image:"", active:true },
  { id:"balmond", name:"Balmond", lanes:["Jungle","EXP Lane"], image:"", active:true },
  { id:"bane", name:"Bane", lanes:["EXP Lane","Jungle"], image:"", active:true },
  { id:"barats", name:"Barats", lanes:["Jungle","EXP Lane"], image:"", active:true },
  { id:"baxia", name:"Baxia", lanes:["Jungle","Roam"], image:"", active:true },
  { id:"beatrix", name:"Beatrix", lanes:["Gold Lane"], image:"", active:true },
  { id:"belerick", name:"Belerick", lanes:["Roam"], image:"", active:true },
  { id:"benedetta", name:"Benedetta", lanes:["EXP Lane","Jungle"], image:"", active:true },
  { id:"brody", name:"Brody", lanes:["Gold Lane"], image:"", active:true },
  { id:"bruno", name:"Bruno", lanes:["Gold Lane"], image:"", active:true },
  { id:"carmilla", name:"Carmilla", lanes:["Roam"], image:"", active:true },
  { id:"cecilion", name:"Cecilion", lanes:["Mid Lane"], image:"", active:true },
  { id:"chang-e", name:"Chang'e", lanes:["Mid Lane"], image:"", active:true },
  { id:"chip", name:"Chip", lanes:["Roam"], image:"", active:true },
  { id:"chou", name:"Chou", lanes:["EXP Lane","Roam"], image:"", active:true },
  { id:"claude", name:"Claude", lanes:["Gold Lane"], image:"", active:true },
  { id:"clint", name:"Clint", lanes:["Gold Lane"], image:"", active:true },
  { id:"cyclops", name:"Cyclops", lanes:["Mid Lane"], image:"", active:true },
  { id:"diggie", name:"Diggie", lanes:["Roam"], image:"", active:true },
  { id:"dyrroth", name:"Dyrroth", lanes:["EXP Lane","Jungle"], image:"", active:true },
  { id:"edith", name:"Edith", lanes:["EXP Lane","Roam"], image:"", active:true },
  { id:"esmeralda", name:"Esmeralda", lanes:["EXP Lane"], image:"", active:true },
  { id:"estes", name:"Estes", lanes:["Roam"], image:"", active:true },
  { id:"eudora", name:"Eudora", lanes:["Mid Lane"], image:"", active:true },
  { id:"fanny", name:"Fanny", lanes:["Jungle"], image:"", active:true },
  { id:"faramis", name:"Faramis", lanes:["Mid Lane","Roam"], image:"", active:true },
  { id:"floryn", name:"Floryn", lanes:["Roam"], image:"", active:true },
  { id:"franco", name:"Franco", lanes:["Roam"], image:"", active:true },
  { id:"fredrinn", name:"Fredrinn", lanes:["Jungle","EXP Lane"], image:"", active:true },
  { id:"freya", name:"Freya", lanes:["EXP Lane","Jungle"], image:"", active:true },
  { id:"gloo", name:"Gloo", lanes:["EXP Lane","Roam"], image:"", active:true },
  { id:"gord", name:"Gord", lanes:["Mid Lane"], image:"", active:true },
  { id:"granger", name:"Granger", lanes:["Jungle","Gold Lane"], image:"", active:true },
  { id:"grock", name:"Grock", lanes:["Roam","EXP Lane"], image:"", active:true },
  { id:"guinevere", name:"Guinevere", lanes:["EXP Lane","Jungle"], image:"", active:true },
  { id:"gusion", name:"Gusion", lanes:["Jungle","Mid Lane"], image:"", active:true },
  { id:"hanabi", name:"Hanabi", lanes:["Gold Lane"], image:"", active:true },
  { id:"hanzo", name:"Hanzo", lanes:["Jungle"], image:"", active:true },
  { id:"harith", name:"Harith", lanes:["Mid Lane","Gold Lane"], image:"", active:true },
  { id:"harley", name:"Harley", lanes:["Jungle","Mid Lane"], image:"", active:true },
  { id:"hayabusa", name:"Hayabusa", lanes:["Jungle"], image:"", active:true },
  { id:"helcurt", name:"Helcurt", lanes:["Jungle","Roam"], image:"", active:true },
  { id:"hilda", name:"Hilda", lanes:["EXP Lane","Roam"], image:"", active:true },
  { id:"hylos", name:"Hylos", lanes:["Roam","Jungle"], image:"", active:true },
  { id:"irithel", name:"Irithel", lanes:["Gold Lane"], image:"", active:true },
  { id:"ixia", name:"Ixia", lanes:["Gold Lane"], image:"", active:true },
  { id:"jawhead", name:"Jawhead", lanes:["EXP Lane","Roam"], image:"", active:true },
  { id:"johnson", name:"Johnson", lanes:["Roam"], image:"", active:true },
  { id:"joy", name:"Joy", lanes:["Jungle","EXP Lane"], image:"", active:true },
  { id:"julian", name:"Julian", lanes:["Jungle","Mid Lane"], image:"", active:true },
  { id:"kadita", name:"Kadita", lanes:["Mid Lane","Roam"], image:"", active:true },
  { id:"kagura", name:"Kagura", lanes:["Mid Lane"], image:"", active:true },
  { id:"kaja", name:"Kaja", lanes:["Roam","EXP Lane"], image:"", active:true },
  { id:"karina", name:"Karina", lanes:["Jungle"], image:"", active:true },
  { id:"karrie", name:"Karrie", lanes:["Gold Lane"], image:"", active:true },
  { id:"khaleed", name:"Khaleed", lanes:["EXP Lane","Roam"], image:"", active:true },
  { id:"khufra", name:"Khufra", lanes:["Roam"], image:"", active:true },
  { id:"kimmy", name:"Kimmy", lanes:["Gold Lane","Mid Lane"], image:"", active:true },
  { id:"lancelot", name:"Lancelot", lanes:["Jungle"], image:"", active:true },
  { id:"lapu-lapu", name:"Lapu-Lapu", lanes:["EXP Lane"], image:"", active:true },
  { id:"layla", name:"Layla", lanes:["Gold Lane"], image:"", active:true },
  { id:"leomord", name:"Leomord", lanes:["Jungle","EXP Lane"], image:"", active:true },
  { id:"lesley", name:"Lesley", lanes:["Gold Lane"], image:"", active:true },
  { id:"ling", name:"Ling", lanes:["Jungle"], image:"", active:true },
  { id:"lolita", name:"Lolita", lanes:["Roam"], image:"", active:true },
  { id:"lunox", name:"Lunox", lanes:["Mid Lane","Gold Lane"], image:"", active:true },
  { id:"luo-yi", name:"Luo Yi", lanes:["Mid Lane"], image:"", active:true },
  { id:"lylia", name:"Lylia", lanes:["Mid Lane"], image:"", active:true },
  { id:"martis", name:"Martis", lanes:["Jungle","EXP Lane"], image:"", active:true },
  { id:"mathilda", name:"Mathilda", lanes:["Roam"], image:"", active:true },
  { id:"melissa", name:"Melissa", lanes:["Gold Lane"], image:"", active:true },
  { id:"minotaur", name:"Minotaur", lanes:["Roam"], image:"", active:true },
  { id:"moskov", name:"Moskov", lanes:["Gold Lane"], image:"", active:true },
  { id:"nana", name:"Nana", lanes:["Mid Lane"], image:"", active:true },
  { id:"natalia", name:"Natalia", lanes:["Roam","Jungle"], image:"", active:true },
  { id:"nolan", name:"Nolan", lanes:["Jungle"], image:"", active:true },
  { id:"novaria", name:"Novaria", lanes:["Mid Lane"], image:"", active:true },
  { id:"odette", name:"Odette", lanes:["Mid Lane"], image:"", active:true },
  { id:"paquito", name:"Paquito", lanes:["EXP Lane","Jungle"], image:"", active:true },
  { id:"pharsa", name:"Pharsa", lanes:["Mid Lane"], image:"", active:true },
  { id:"popol-kupa", name:"Popol and Kupa", lanes:["Gold Lane"], image:"", active:true },
  { id:"rafaela", name:"Rafaela", lanes:["Roam"], image:"", active:true },
  { id:"roger", name:"Roger", lanes:["Jungle","Gold Lane"], image:"", active:true },
  { id:"ruby", name:"Ruby", lanes:["EXP Lane","Roam"], image:"", active:true },
  { id:"saber", name:"Saber", lanes:["Jungle","Roam"], image:"", active:true },
  { id:"selena", name:"Selena", lanes:["Roam","Mid Lane"], image:"", active:true },
  { id:"silvanna", name:"Silvanna", lanes:["EXP Lane","Roam"], image:"", active:true },
  { id:"sun", name:"Sun", lanes:["EXP Lane","Jungle"], image:"", active:true },
  { id:"terizla", name:"Terizla", lanes:["EXP Lane"], image:"", active:true },
  { id:"tigreal", name:"Tigreal", lanes:["Roam"], image:"", active:true },
  { id:"uranus", name:"Uranus", lanes:["EXP Lane"], image:"", active:true },
  { id:"vale", name:"Vale", lanes:["Mid Lane"], image:"", active:true },
  { id:"valentina", name:"Valentina", lanes:["Mid Lane"], image:"", active:true },
  { id:"valir", name:"Valir", lanes:["Mid Lane"], image:"", active:true },
  { id:"vexana", name:"Vexana", lanes:["Mid Lane"], image:"", active:true },
  { id:"wanwan", name:"Wanwan", lanes:["Gold Lane"], image:"", active:true },
  { id:"xavier", name:"Xavier", lanes:["Mid Lane"], image:"", active:true },
  { id:"yin", name:"Yin", lanes:["EXP Lane","Jungle"], image:"", active:true },
  { id:"yve", name:"Yve", lanes:["Mid Lane"], image:"", active:true },
  { id:"yu-zhong", name:"Yu Zhong", lanes:["EXP Lane"], image:"", active:true },
  { id:"yuzhong", name:"Yu Zhong", lanes:["EXP Lane"], image:"", active:false },
  { id:"zilong", name:"Zilong", lanes:["EXP Lane","Jungle"], image:"", active:true }
];
