(() => {
  'use strict';
  const $=(id)=>document.getElementById(id); let timer=null; let lastSerialized='';
  function values(){return {fullName:$('fullName').value.trim(),username:$('username').value.trim().toLowerCase(),photoURL:$('photoURL').value.trim(),bio:$('bio').value.trim(),country:$('country').value.trim(),mainGame:$('mainGame').value,mainRole:$('mainRole').value,rank:$('rank').value.trim(),playerId:$('playerId').value.trim()};}
  function status(message,type=''){const el=$('saveStatus');if(el){el.textContent=message;el.className=`mh-status ${type}`;}}
  function render(state){const p=state.profile||{},u=state.user;$('fullName').value=p.fullName||u.displayName||'';$('username').value=p.username||'';$('email').value=u.email||'';$('photoURL').value=p.photoURL||u.photoURL||'';$('bio').value=p.bio||'';$('country').value=p.country||'';$('mainGame').value=p.mainGame||'Honor of Kings';$('mainRole').value=p.mainRole||'';$('rank').value=p.rank||'';$('playerId').value=p.playerId||'';const image=$('profilePhoto');image.src=p.photoURL||u.photoURL||window.MOBAHub.DEFAULT_AVATAR;image.onerror=()=>{image.onerror=null;image.src=window.MOBAHub.DEFAULT_AVATAR;};$('profileName').textContent=p.fullName||u.displayName||'MOBA HUB User';$('profileUsername').textContent=p.username?`@${p.username}`:'Complete your username';lastSerialized=JSON.stringify(values());status('All changes are saved.','success');}
  async function save(){const state=MOBAHub.state;if(!state.user||!state.db)return;const data=values();if(data.fullName.length<2){status('Full name must contain at least 2 characters.');return;}if(data.username&&!/^[a-z0-9_]{3,20}$/.test(data.username)){status('Username must be 3–20 letters, numbers, or underscores.');return;}const serialized=JSON.stringify(data);if(serialized===lastSerialized)return;status('Saving…');try{const userRef=state.db.collection('users').doc(state.user.uid);await state.db.runTransaction(async tx=>{const userSnap=await tx.get(userRef);const oldUsername=String(userSnap.data()?.username||'').toLowerCase();if(data.username!==oldUsername){if(data.username){const newRef=state.db.collection('usernames').doc(data.username);const newSnap=await tx.get(newRef);if(newSnap.exists&&newSnap.data()?.uid!==state.user.uid)throw new Error('This username is already in use.');tx.set(newRef,{uid:state.user.uid,email:String(state.user.email||''),updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});}if(oldUsername)tx.delete(state.db.collection('usernames').doc(oldUsername));}else if(data.username){tx.set(state.db.collection('usernames').doc(data.username),{uid:state.user.uid,email:String(state.user.email||''),updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});}tx.set(userRef,{...data,email:state.user.email||'',updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});});if(state.user.displayName!==data.fullName)await state.user.updateProfile({displayName:data.fullName});state.profile={...(state.profile||{}),...data};lastSerialized=serialized;render(state);MOBAHub.renderAccount();status('Saved automatically.','success');}catch(error){status(error.message||'Unable to save changes.');}}
  MOBAHub.onReady(state=>{render(state);document.querySelectorAll('[data-profile-field]').forEach(input=>{input.addEventListener('input',()=>{status('Unsaved changes');clearTimeout(timer);timer=setTimeout(save,700);});input.addEventListener('change',save);});$('saveNow')?.addEventListener('click',save);});
})();
